name: "iOS Build"

on:
  workflow_call:
  
jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 19
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: "npm"

      - name: Install Node modules
        run: npm ci
      - name: Restore Pods cache
        uses: actions/cache@v3
        with:
          path: |
            ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install pod dependencies
        run: cd example/ios && bundle install && bundle exec pod install && cd ..

      - name: Build and Test iOS
        run: xcodebuild clean build test -workspace example/ios/plaidRNDemo.xcworkspace -scheme plaidRNDemo -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.2'